### ISSUE TITLE
ESAPI, mod_security, ASIC?

### ISSUE THREAD

**Issue by paradisaeidae** [tenderlove/the_metal#6]
ESAPI, no Ruby?
Are there intersections with this project?
https://www.owasp.org/index.php/Category:OWASP_Enterprise_Security_API#tab=Project_Details
Can we accommodate this: http://modsecurity.org/
Is there a possible export function which would wrap a Rack::App in a bucket to throw towards an ASIC? https://en.wikipedia.org/wiki/Application-specific_integrated_circuit

MarkT

**Comment by tenderlove** [comment]
We can probably do this stuff, but the point of this spike is to figure out Rack 2.0 API.
